### ISSUE TITLE
No such file or directory 

### ISSUE THREAD

**Issue by shivangbaveja** [speedinghzl/pytorch-segmentation-toolbox#7]
I was trying to run the model without any modifications on google cloud with V100 GPU. I got following error:

RuntimeError: CUDA Error encountered in <function CompiledLib.bn_mean_var_cuda at 0x7fd263866c80>
Traceback (most recent call last):
  File "evaluate.py", line 253, in <module>
    main()
  File "evaluate.py", line 198, in main
    saved_state_dict = torch.load(args.restore_from)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')

Is it related to training on V100 GPU. Currently I have only one GPU attached.

**Comment by speedinghzl** [comment]
@shivangbaveja I do not see any errors about "No such file or directory" in your error. Have you checked the trained model path is correct?

**Comment by shivangbaveja** [comment]
In my case, the error came when I was training on V-100 GPU. I tried running on a different GPU (I think P50) and that solved the issue. I am no longer working on this so closing this issue.

**Comment by speedinghzl** [comment]
@amiltonwong The first error leads to the second one. you need 4 x 12g GPUs to run this repo If you want to reproduce high performance (~78.5% mIOU on val set). Or, you just need to set a small batch size (2 images per GPU).
